### ISSUE TITLE
kubernetesVersionSelection does not work as expected.

### ISSUE THREAD

**Issue by imusmanmalik** [carvel-dev/kapp-controller#1117]
**What steps did you take:**

Using: `kctrl` - `v0.44.6`

As per the docs -> https://carvel.dev/kapp-controller/docs/v0.43.2/packaging/#requiring-specific-versions-of-kubernetes

I have my Package YAML as:

```yaml
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: my-app.io.0.0.0
spec:
  kubernetesVersionSelection:
    constraints: ">=1.22.0 <1.27.0"
```

**What happened:**

When i use kctrl to release the package and copy the artifacts to a directory i cannot find this information anywhere inside package.yml 

```yaml
  kubernetesVersionSelection:
    constraints: ">=1.22.0 <1.27.0"
```

Is not part of the `spec` when package is released using `kctrl`

**What did you expect:**

i would expect this to be there in the released Package Repository `package.yml` file to be later parsed and validated by `kapp-controller` when Package is installed.

**Environment:**

- kctrl - v0.44.6

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
