### ISSUE TITLE
Failed to Get Package use c.Get(ctx, key, obj)

### ISSUE THREAD

**Issue by KevenNock** [carvel-dev/kapp-controller#1152]
**What steps did you take:**
I use `controlleruitl.CreateOrUpdate` to  create Package
```go
        var pkg datapack.Package
	pkgName := strings.ToLower(solutionType)
	// Name Must be of the form '<spec.refName>.<spec.version>' (Note the period)
	pkg.Name = strings.Join([]string{pkgName, c.HelmChart.Version}, ".")
	pkg.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "data.packaging.carvel.dev",
		Version: "v1alpha1",
		Kind:    "Package",
	})
	pkg.Namespace = r.dsSystemNamespace
	pkg.Spec.RefName = pkgName
	pkg.Spec.Version = c.HelmChart.Version
	pkg.Spec.Template.Spec = new(kapp.AppSpec)
	pkg.Spec.Template.Spec.Fetch = append(pkg.Spec.Template.Spec.Fetch, kapp.AppFetch{HelmChart: c.HelmChart})
      
        ret, e := controllerutil.CreateOrUpdate(ctx, r.Client, &pkg, func() error {
		pkg.SetLabels(map[string]string{labelKeyCreatedBy: labelValueVCDDS})
		pkg.SetAnnotations(map[string]string{dsconfigRefAnnotation: name})
		return nil
	})

// It returns the executed operation and an error.
func CreateOrUpdate(ctx context.Context, c client.Client, obj client.Object, f MutateFn) (OperationResult, error) {
	key := client.ObjectKeyFromObject(obj)
	if err := c.Get(ctx, key, obj); err != nil {
		if !apierrors.IsNotFound(err) {
			return OperationResultNone, err
		}
		if err := mutate(f, key, obj); err != nil {
```

**What happened:**
```bash
 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167: failed to list *datapackaging.Package: no kind "ListOptions" is registered for the internal version of group "data.packaging.carvel.dev" in scheme "pkg/runtime/scheme.go:100"
E0331 18:29:32.013859   61911 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167: Failed to watch *datapackaging.Package: failed to list *datapackaging.Package: no kind "ListOptions" is registered for the internal version of group "data.packaging.carvel.dev" in scheme "pkg/runtime/scheme.go:100"
```

**What did you expect:**
get the Package object

**Anything else you would like to add:**

**Environment:**
```yaml
 annotations:
    deployment.kubernetes.io/revision: "1"
    kapp-controller.carvel.dev/version: v0.44.6
    kbld.k14s.io/images: |
      - origins:
        - local:
            path: /home/runner/work/kapp-controller/kapp-controller
        - git:
            dirty: false
            remoteURL: https://github.com/carvel-dev/kapp-controller
            sha: d4a8f331d77b8e8046d65f1578206d31a5e33938
            tags:
            - v0.44.6
        url: ghcr.io/carvel-dev/kapp-controller@sha256:eea5193161109c3685edad596b4b740a0683a0cb892f2a9cf94af96c6008203b
```

```bash 
$ kubectl version 
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-18T02:16:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-09-01T23:30:43Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
```

Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
