### ISSUE TITLE
Allow syncing to be disabled

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#118]
**Describe the problem/challenge you have**

I would like to be able to disable syncing entirely for an App and only have that App updated by explicit request from a client. 

**Describe the solution you'd like**

On the App spec, there should be some way to disable syncing for an App and then reconciliation only happens via a client request to kapp-controller. 

```yaml
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-app
  namespace: default
spec:
  disableSyncPeriod: true
  serviceAccountName: default-ns-sa
  fetch:
  - git:
      url: https://github.com/k14s/k8s-simple-app-example
      ref: origin/develop
      subPath: config-step-2-template
  template:
  - ytt:
      inline:
        pathsFrom:
        - secretRef:
            name: simple-app-values
  deploy:
  - kapp: {}
```
