### ISSUE TITLE
InstalledPackage authors should be able to provide overlays

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#123]
In the current alpha, package consumers aren't able to customize package installation beyond what is exposed via data values. There should be a way to allow consumers to provide overlays via an InstalledPackage which will be applied at some point.

This may be similar to #122, but has a slight difference since package authors can't know where to inject consumer provided overlays. One idea is to just append a ytt step at the end of all other template steps which just includes the overlays, but this could suffer from some drawbacks like the overlays won't have access to data values, etc.

**Comment by voor** [comment]
This seems like it'll be fairly critical for adding in things like sops that is not explicitly declared in certain packages.

**Comment by cppforlife** [comment]
we want to take our time designing first class feature (on InstalledPackage CR) for using ytt overlays on top of ytt templates, helm templates, and other templaters.

meanwhile to accommodate advanced users, we will add an experimental feature that would allow to provide custom ytt overlays for packages that are based on ytt templates (this annotation would not work for packages that use helm template). this experimental feature would be exposed via an annotation on InstalledPackage:

```yaml
kind: InstalledPackage
metadata:
  name: foo
  annotations:
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: my-overlays
spec:
   ...
---
kind: Secret
metadata:
  name: my-overlays
stringData:
  my-overlay.yml: |
    #@ load("@ytt:overlay", ...)
    ...
```

TBD still chewing on annotation name.
