### ISSUE TITLE
The PackageInstall CRD documentation is not up to date

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/kapp-controller#1275]
The documentation in the Package Install Custom Resource has a TODO already done.
This particular instance is https://github.com/carvel-dev/kapp-controller/blob/6eb91df8648dda30cb919ec1d9e2add7781ceb3d/pkg/apis/packaging/v1alpha1/package_install.go#L102-L104.
But we should make sure that we go through the CRDs to see if there is another instance where we have TODOs that are no longer valid.

**Comment by rajathagasthya** [comment]
The [PackageInstall CRD documentation](https://carvel.dev/kapp-controller/docs/v0.46.0/packaging/#package-install) also says `status.packageRef` exists, but no such type exists in the API.

```yaml
# Populated by the controller
status:
  packageRef:
    # Kubernetes resource name of the package chosen against the constraints
    name: fluent-bit.tkg.vmware.com.v1.5.3
```
