### ISSUE TITLE
Leverage new ytt proposal in App Spec

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#129]
ytt has a [new proposal](https://github.com/vmware-tanzu/carvel/blob/d6b88588f7f5943814ba05008cd5edb370d96504/proposals/ytt/003-raw-data-values/README.md) to add the ability to provide raw, unannotated yaml documents as data value documents via the command line. It could be helpful to adapt the App API to include a way to leverage this new feature. This would also improve the packaging APIs as it would the specific templating engine used by a package would no longer leak to the end user (end user wouldn't need to include #@data/values in the values when installing a package)

A suggestion for what this could look like is to add the valueFrom key to the ytt templating step. This will behave exactly how the helm templating valuesFrom option behaves, providing greater consistency across the APIs. An example:
```yaml
...
 template:
    - ytt:
        valuesFrom:
        - secretRef:
              name: secret-name
          - configMapRef:
              name: cfgmap-name
          - path: values/shared.yml
...
```

kapp-controller will then turn these inputs in to files provided to ytt and marked with the suggested file mark `type:yaml-data-values`.
