### ISSUE TITLE
app cr downward api fails when referencing annotations with a dot

### ISSUE THREAD

**Issue by jorgemoralespou** [carvel-dev/kapp-controller#1328]
**What steps did you take:**
I have an App with a downwardAPI reference to an annotation with a . in it:

```
  template:
    - ytt:
        ignoreUnknownComments: true
        paths:
          - workshops
        valuesFrom:
          - downwardAPI:
              items:
              - name: name
                fieldPath: metadata.annotations['educates.bundle.name']
```

**What happened:**
It failed to get the value from the `educates.bundle.name` saying can't find value in `educates`. 

**What did you expect:**
I would have expected to resolve fine

**Anything else you would like to add:**
I have tried esccaping the dots, as it's described for the name of the value (e.g:  `metadata.annotations['educates\\.bundle\\.name']`

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`): v0.46.1
- Kubernetes version (use `kubectl version`): v1.25.12-eks-2d98532

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by neil-hickey** [comment]
What error did you get when you use `metadata.annotations['educates\\.bundle\\.name']` ? @jorgemoralespou 

There is a specific test in KC for this use-case. So I'm a little surprised it's not working for you: https://github.com/carvel-dev/kapp-controller/blob/96bbb5806b46fa6bbc5e95028d129c3e1f6d4e20/pkg/template/values_test.go#L180

Hmm, I guess this test is specific to `labels` not annotations, but I believe the code-path is the same

**Comment by jorgemoralespou** [comment]
I get this error:

```
Preparing template values: educates is not found
```

**Comment by jorgemoralespou** [comment]
Created a quick reproducer:

```
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  annotations:
    educates.cluster.name: test
  name: test
spec:
  syncPeriod: 0h1m0s
  serviceAccountName: default
  fetch:
    - inline:
        paths:
          sample.yaml: |
            #@ load("@ytt:data", "data")
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: workshops-global.app
            data:
              spec: #@ data.values.name
      path: ytt
  template:
    - ytt:
        ignoreUnknownComments: true
        paths:
          - ytt
        valuesFrom:
          - downwardAPI:
              items:
                - fieldPath: metadata.annotations['educates\\.cluster\\.name']
                  name: name
  deploy:
    - kapp:
        rawOptions:
          - --app-changes-max-to-keep=5
          - --wait-timeout=5m
```

And if you change annotation to `educates_cluster_name` both in the annotation and in the downwarAPI it works (as it's a sample reproducer there's an error saying the CM can no be created due to the SA privileges, but that's other thing)
