### ISSUE TITLE
Version 0.48.0 introduced bug/regression when installing using kubeconfig to separate cluster.

### ISSUE THREAD

**Issue by GrahamDumpleton** [carvel-dev/kapp-controller#1332]
**What steps did you take:**

Using latest 0.48.0. This problem doesn't arise with 0.47.0.

Using `App` resources to install stuff into a separate cluster using a `kubeconfig`. Eg. something like:

```
metadata:
  name: vcluster-session-educates-cli-w03-s001
  namespace: educates-cli-w03
spec:
  cluster:
    kubeconfigSecretRef:
      key: config
      name: vc-shared-vcluster
    namespace: default
```

**What happened:**

The package will not be installed and fails with a message:

```
stderr: 'kapp: Error: namespaces "educates-cli-w03" not found'
stdout: 'Target cluster ''https://shared-vcluster.educates-cli-w03.svc.cluster.local/''(nodes: educates-control-plane)'
```

In other words, `kapp-controller` is now expecting a namespace with name the same as the namespace containing the `App` in the originating cluster, to exist in the target cluster, even though this should not be required.

In 0.47.0 there was no such requirement and everything worked fine.

Setting the new `defaultNamespace` property added in 0.48.0 doesn't workaround the regression.

**What did you expect:**

Should have worked like in 0.47.0 when using `kubeconfig` to install in a different cluster.

**Anything else you would like to add:**

Nope.

**Environment:**

- kapp Controller version: 0.48.0

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
