### ISSUE TITLE
`kctrl`: Helm array values with an empty default should still get an `items` field in their OpenAPI schema

### ISSUE THREAD

**Issue by gcapizzi** [carvel-dev/kapp-controller#1464]
**What steps did you take:**

`kctrl package release --openapi-schema` of a package using a `helmTemplate`.

**What happened:**

Helm array values with an empty default, e.g.
```yaml
# -- Add custom arguments to the Crossplane pod.
args: []
```
don't get an `items` field in OpenAPI:
```yaml
args:
  default: []
  description: Add custom arguments to the Crossplane pod.
  type: array
```

**What did you expect:**

An `items` field, as it's [required in OpenAPI](https://swagger.io/docs/specification/data-models/data-types/#array):
```yaml
args:
  default: []
  description: Add custom arguments to the Crossplane pod.
  type: array
  items: {}
```

**Anything else you would like to add:**

Using `{}` to provide an empty schema for `items` is [valid](https://swagger.io/docs/specification/data-models/data-types/#mixed-array) and acceptable, as in this case we don't have any information about the type of the array items. This results in the array accepting arbitrary types.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
