### ISSUE TITLE
Support forcing basic authentication for fetches that use git

### ISSUE THREAD

**Issue by voor** [carvel-dev/kapp-controller#1485]
**Describe the problem/challenge you have**
See: https://github.com/carvel-dev/vendir/issues/361 for upstream `vendir` issue.

This is the downstream issue that is necessary to bubble up this feature to the kapp-controller app CR.

**Describe the solution you'd like**
```
    - git:
        forceHTTPBasicAuth: true # Adding this configuration option.
        secretRef:
          name: secret-name # Same formatted secret, unchanged, includes username and password.
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
