### ISSUE TITLE
PackageRepo secretRefs need to exist in kapp-controller namespace

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#163]
**What steps did you take:**

Create a PackageRepository with a `secretRef` for fetching an image. A private registry that requires authentication is how this originally came up.

```
apiVersion: install.package.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: basic.vmware.com
spec:
  fetch:
    image:
      url: host.com/username/image:v0.1.0
      secretRef:
        name: secret-name
...
```

**What happened:**

The secret for the image secretRef was available on the cluster, but the image for the PackageRepo could not be fetched because the secret for the secretRef could not be found. 

This is because the App for a PackageRepo is always created in the kapp-controller namespace. So users need to know to create secrets in the kapp-controller namespace in order to successfully authenticate against a private registry.

**What did you expect:**

A way to specify the location of the secret such that the PackageRepository creator does not need to think about the namespace where the associated App is deployed to.

**Anything else you would like to add:**

One possible approach would be to allow users to pick the namespace where the PackageRepository's App CR is deployed to. This could allow users to create the PackageReposiotry App CR in a namespace where secrets are already created.

This issue will also depend on the resolution of #108.
