### ISSUE TITLE
introduce AppDefinition CRD

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#19]
AppDefinition allows to expose App creation as a dedicated CRD so that "configuration details" are hidden from the App creator. For example:

AppDefinition named `my-app` specifies how to create `MyApp/v1alpha1` by defining App template (represented via App CRD's spec section). Users that want to create new instance of MyApp use create MyApp CR and fill it out with data values (if any required).

```yaml
apiVersion: kappctrl.k14s.io/v1alpha1
kind: AppDefinition
metadata:
  name: myapp
spec:
  crd:
    apiGroup: apps.co.com
    version: v1alpha1
    name: MyApp
  defaults: # <-- ytt data values?
    ...
  template:
    spec: # App CRD spec
      fetch:
      - git: ...
      template:
      - ytt: ...
      deploy:
      - kapp: ...
```

```yaml
apiVersion: apps.co.com/v1alpha1
kind: MyApp
metadata:
  name: app1
  namespace: apps
spec:
  host: blah.com
status:
  conditions:
  - type: Reconciling
  - type: ReconcileSucceeded
  - type: ReconcileFailed
    reason: Invalid
    message: ...
```
