### ISSUE TITLE
Make More App CR Properties Available Through InstalledPackage CR

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#193]
**Describe the problem/challenge you have**

As a user of kapp-controller's packaging APIs, I would like the ability to configure all relevant App CR properties through the creation of an InstalledPackage. Currently, users are limited to only some of the relevant properties of an App CR.

**Describe the solution you'd like**

Expose the following properties on the InstalledPackage spec:

```yaml
spec:
  # pauses _future_ reconcilation; does _not_ affect
  # currently running reconciliation (optional; default=false)
  paused: true

  # cancels current and future reconciliations (optional; default=false)
  canceled: true

  # Deletion requests for the App will result in the App CR being
  # deleted, but its associated resources will not be deleted 
  # (optional; default=false; v0.18.0+)
  noopDelete: true

  # specifies the length of time to wait, in time + unit
  # format, before reconciling. Always >= 30s. If value below
  # 30s is specified, 30s will be used. (optional; v0.9.0+; default=30s)
  syncPeriod: 1m

  # specifies that app should be deployed to destination cluster;
  # by default, cluster is same as where this resource resides (optional; v0.5.0+)
  cluster:
    # specifies namespace in destination cluster (optional)
    namespace: ns2
    # specifies secret containing kubeconfig (required)
    kubeconfigSecretRef:
      # specifies secret name within app's namespace (required)
      name: cluster1
      # specifies key that contains kubeconfig (optional)
      key: value
```

**Anything else you would like to add:**

We should be able to pass the InstalledPackage properties to the App when it is created as shown here: https://github.com/vmware-tanzu/carvel-kapp-controller/blob/27a5c47594740b9e25b14a53d88b2155fa9362de/pkg/installedpkg/app.go#L22

These fields should be documented at https://carvel.dev/kapp-controller/docs/latest/packaging/#installedpackage-cr

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
