### ISSUE TITLE
git checkout reference is not a tree

### ISSUE THREAD

**Issue by kramerul** [carvel-dev/kapp-controller#20]
We are using the following configuration to install cf-for-k8s:

```yaml
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App

metadata:
  name: cf

spec:
  cluster:
    kubeconfigSecretRef:
      name: "cf4k8s-kapp.kubeconfig"
      key: "kubeconfig"
  fetch:
    - git:
        url: https://github.tools.sap/cki/cf-for-k8s-scp.git
        ref: origin/master
        secretRef:
          name: github-tools-sap-token
        subPath: config

  template:
    - ytt:
        inline:
          pathsFrom:
            - secretRef:
                name: cf-values

  deploy:
    - kapp:
        inspect:
          rawOptions: ["--json=true"]
```

When we change `ref: origin/master` to `ref: 11c6cd21ff7100de5bf208aa391912f38c830b32` we get the following error:

```bash
Reconcile failed: Fetching (0): Fetching git repo: Git [checkout 11c6cd21ff7100de5bf208aa391912f38c830b32 --recurse-submodules .]: exit status 128 (stderr: fatal: reference is not a tree: 11c6cd21ff7100de5bf208aa391912f38c830b32
)
```

although the commit `11c6cd21ff7100de5bf208aa391912f38c830b32` exists in the repo.

`git checkout 11c6cd21ff7100de5bf208aa391912f38c830b32 --recurse-submodules .` on the command line works fine.

Running 
```
cd /tmp
rm -rf cf-for-k8s
mkdir cf-for-k8s
cd cf-for-k8s/
git init .
git remote add origin https://github.tools.sap/cki/cf-for-k8s-scp.git
git fetch origin
git checkout 11c6cd21ff7100de5bf208aa391912f38c830b32
```

 inside the kapp-controller docker container also works.
