### ISSUE TITLE
Need Ability to Specify Package Contents/Version

### ISSUE THREAD

**Issue by seemiller** [carvel-dev/kapp-controller#212]
**Describe the problem/challenge you have**

Packages need the ability to specify/declare the software that they contain.

* Package contains 1 piece of software

    Consider the cases where I have multiple packages that bundle the cert-manager software at various versions. 

    | Package Name | Package Version | Contents | Contents Version |
    | --------------- | ---------------- | --------- | ----------------- |
    | cert-mgr | 1.0.0 | cert-manager | 1.1.0 |
    | cert-mgr | 1.0.1 | cert-manager | 1.1.1 |
    | cert-mgr | 1.1.0 | cert-manager | 1.2.0 |
    | cert-mgr | 1.2.0 | cert-manager | 1.3.0 |

    When I load these packages to a PackageRepository and retrieve the list of packages from my cluster, I'll get:

    ```
    NAME                             VERSION         DESCRIPTION
    cert-mgr                         1.0.0
    cert-mgr                         1.0.1
    cert-mgr                         1.1.0
    cert-mgr                         1.2.0
    ```
    There is no indication of what is actually in the package, unless I were to update that information into the description.

* The problem gets worse when there is multiple pieces of software in the package. Consider the case of Prometheus and Alert-Manager bundled together.

    | Package Name | Package Version | Contents | Contents Version |
    | --------------- | ---------------- | --------- | ----------------- |
    | tobs | 1.0.0 | prometheus, alert-manager | 2.25.0, 0.21.0 |
    | tobs | 1.1.0 | prometheus, alert-manager | 2.26.0, 0.22.0 |

    When I load these packages to a PackageRepository and retrieve the list of packages from my cluster, I'll get:

    ```
    NAME                             VERSION         DESCRIPTION
    tobs                             1.0.0
    tobs                             1.1.0
    ```

**Describe the solution you'd like**

I would like the ability to list in the `packageVersion` CR what software is contained in the package and I would like to be able to see that information when retrieved from the cluster.

Modify the `packageVersion` CR:

```yaml
---
apiVersion: package.carvel.dev/v1alpha1
kind: Package
metadata:
  name: simple-app.corp.com.1.0.0
spec:
  refName: simple-app.corp.com
  version: 1.0.0
  software:
  - name: simple-app-controller
    version: 1.0.0
    description: the controller
  - name: foo-webhook
    version: 2.3.4
    description: a foo webhook
  - name: bar-webhook
    version: 3.4.5
    description: a bar webhook
  releaseNotes: |
        Initial release of the simple app package
...
```

I would then like to see that information through the command line

```
NAME                             VERSION         CONTENTS
simple-app.corp.com.1.0.0        1.0.0           simple-app-controller-1.0.0;foo-webhook-2.3.4;bar-webhook-3.4.5
```

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
