### ISSUE TITLE
Need to authencate with embed harbor in vsphere with tanzu when deploying tkg-extension by kapp-controller?

### ISSUE THREAD

**Issue by boyfzb2018** [carvel-dev/kapp-controller#215]
After follow the guide from Jesse Hu, I have fix the issue "certificate signed by unknown authority" when I deployment tkg1.3.1-extention fluentbit, but new error occurs:"Stderr: Error: Syncing directory '0': Syncing directory '.' with image contents: Imgpkg: exit status 1 (stderr: Error: Collecting images: Working with 192.168.104.2/tkgs-cluster-ns/tkg-extensions-templates:v1.3.1_vmware.1: GET https://192.168.104.2/v2/tkgs-cluster-ns/tkg-extensions-templates/manifests/v1.3.1_vmware.1: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:tkgs-cluster-ns/tkg-extensions-templates Type:repository]]"

I using embed harbor in vsphere with tanzu, How can i pass "imagePullSecrets" to kapp-controller pod to authenticate with harbor?
  
the following guide is from Jesse Hu
```
  Here is the ConfigMap solution for supporting custom ca cert for image pulling:

    1. Add the CA cert of your registry server into a file custom-ca-certs.crt

    2. Create a ConfigMap with this file:
       kubectl create configmap custom-ca-certs --from-file=custom-ca-certs.crt -n kapp-controller

    3. Modify the kapp-controller.yaml as below to mount the cert file from the ConfigMap, then kubectl apply it.

    containers:
    - command:
      - /kapp-controller
      ... ...
      volumeMounts:
      - mountPath: /etc/kappctrl-mem-tmp
        name: template-fs
      - mountPath: /etc/ssl/certs/custom-ca-certs.crt
        name: custom-ca-certs
        readOnly: true
        subPath: custom-ca-certs.crt
    ... ...
    volumes:
    - emptyDir:
        medium: Memory
      name: template-fs
    - configMap:
        name: custom-ca-certs
      name: custom-ca-certs
```
