### ISSUE TITLE
kapp error when KAPP_KUBECONFIG_YAML set to empty

### ISSUE THREAD

**Issue by Arttii** [carvel-dev/kapp-controller#24]
I encountered a bug, where KAPP_KUBECONFIG_YAML is being set to empty in version >0.6, which somehow leads to yaml formatting errors for my yaml specs. 

Just changing https://github.com/k14s/kapp-controller/blob/develop/pkg/deploy/kapp.go#L196 to just do `!= ""` fixes the issue. Is there a reason for using the `len` approach?

**Comment by cppforlife** [comment]
im not sure i understand what error you are encountering. `len(...) > 0` and `... != ""` is the same thing. how does your App CR look like?

**Comment by Arttii** [comment]
Ya sorry, I was not very clear. For this app CR

```
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: ds-tools-jupyterhub
  namespace: default
spec:
  serviceAccountName: cluster-admin-sa
  fetch:
  - image:
        # Docker image url; unqualified, tagged, or
        # digest references supported (required)
        url: docker/image
        # secret with auth details (optional)
        secretRef:
          name: auth
        subPath: ds-tools/jupyterhub
  template:
  - ytt:
        ignoreUnknownComments: true
        strict: false
  deploy:
  - kapp: {}

```
The `len` condition evaluates to true, even though no GenericOpt is set. This leads to the kapp cmd environment containing KAPP_KUBECONFIG_YAML="", which leads to the kapp deploy exiting with something like `mapping values are not allowed in this context`. This does not happen when using the 0.6 version.
