### ISSUE TITLE
Support a ytt inline values option for ease of use

### ISSUE THREAD

**Issue by voor** [carvel-dev/kapp-controller#25]
I really like doing the following fairly often:

```yaml
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        paths:
          somemorevalues.yaml: |
            #@data/values
            ---
            stuff: that
            can: go
            here: true
```

Unfortunately you lose the power of native yaml syntax highlighting and other convenience stuff.  If you added in support for just `inline.values` you could instead have the following:

```yaml
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        values:
          stuff: that
          can: go
          here: true
```

It's more of a convenience thing, but it also lowers the barrier because someone would need to know the little hack to include a data/values file directly.
