### ISSUE TITLE
watch for changes to configmap/secret and trigger App reconcile

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#26]
this would make syncPeriod configuration more useful (e.g. it could be set higher, and App can try to react to "input" changes proactively). i'd like to have this mechanims pave the way for "watching" of other resources used by App.

**Comment by cppforlife** [comment]
current thinking:

```yaml
apiVersion: kappctrl.k14s.io/v1alpha1
kind: AppReconcileRequest
metadata:
  generateName: app-name-
spec:
  appRef:
    name: app-name
  reason: "ConfigMap x contents changed."
status:
  conditions:
  - type: Enqueued
```

controller would delete AppReconcileRequest after X minutes after it was enqueued.

alternatively, we could add some field like `spec.reconcileMarker` on `App` resource to force metadata.generation to be bumped, hence would reconcile. downside to that is it makes App's spec possibly conflict with what user is entering (if we do not add kapp rebase rules for that) and less declarative.
