### ISSUE TITLE
basic deployment of OCI bundle not working

### ISSUE THREAD

**Issue by sebgoa** [carvel-dev/kapp-controller#266]
**What steps did you take:**
Packaged a simple Pod manifest running nginx with imgpkg 
Pushed the OCI bundle to gcr
Tried to deploy an app with kapp

**What happened:**

from the CLI or the controller

```
$ kapp deploy -a foobar -f app.yaml
Target cluster 'https://35.233.212.162' (nodes: gke-cluster-1-default-pool-c639656a-d20k, 2+)

Changes

Namespace  Name    Kind  Conds.  Age  Op  Op st.  Wait to    Rs    Ri
default    testtm  App   1/1 t   3m   -   -       reconcile  fail  Reconcile failed:  (message:
                                                                   Deploying: Error (see
                                                                   .status.usefulErrorMessage for
                                                                   details))

Op:      0 create, 0 delete, 0 update, 1 noop
Wait to: 1 reconcile, 0 delete, 0 noop

Continue? [yN]: y

12:40:38PM: ---- applying 1 changes [0/1 done] ----
12:40:38PM: noop app/testtm (kappctrl.k14s.io/v1alpha1) namespace: default
12:40:38PM: ---- waiting on 1 changes [0/1 done] ----
12:40:39PM: fail: reconcile app/testtm (kappctrl.k14s.io/v1alpha1) namespace: default
12:40:39PM:  ^ Reconcile failed:  (message: Deploying: Error (see .status.usefulErrorMessage for details))

kapp: Error: waiting on reconcile app/testtm (kappctrl.k14s.io/v1alpha1) namespace: default:
  Finished unsuccessfully (Reconcile failed:  (message: Deploying: Error (see .status.usefulErrorMessage for details)))
```

and

```
  usefulErrorMessage: |-
    kapp: Error: Validation errors:
    - Expected 'metadata.name' on resource 'imageslock/ (imgpkg.carvel.dev/v1alpha1) cluster' to be non-empty (stdin doc 2)
```

My app.yaml

```
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: testtm
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  cluster: {}
  fetch:
  - imgpkgBundle:
      image: gcr.io/triggermesh/foo
  template:
  - ytt: {}
  deploy:
  - kapp: {}
```

My imageslock:

```
$ cat foo/.imgpkg/images.yml 
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
- image: index.docker.io/nginx@sha256:47ae43cdfc7064d28800bc42e79a429540c7c80168e8c8952778c0d5af1c09db
  annotations:
    kbld.carvel.dev/id: docker.io/nginx
```

My pod.yaml in the bundle

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
```

**Comment by danielhelfand** [comment]
Hi @sebgoa,

One thing I notice about your App yaml is you are missing a kbld step under the template section of the App spec. This is needed to make use of your bundle's ImagesLock (i.e. images.yml). Could you give this a try?

```yaml
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: testtm
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  cluster: {}
  fetch:
  - imgpkgBundle:
      image: gcr.io/triggermesh/foo
  template:
  - ytt: {}
  - kbld:
        paths:
        - "-"
        - .imgpkg/images.yml
  deploy:
  - kapp: {}
```

**Comment by sebgoa** [comment]
not quite

```
  usefulErrorMessage: |-
    kapp: Error: Expected to find kind 'imgpkg.carvel.dev/v1alpha1/Bundle', but did not:
    - Kubernetes API server did not have matching apiVersion + kind
    - No matching CRD was found in given configuration
```

**Comment by sebgoa** [comment]
Basically I am trying to deploy https://github.com/vmware-tanzu/carvel-imgpkg/tree/develop/examples/basic-step-2 after it has been pushed as an OCI bundle with `imgpkg`

**Comment by ewrenn8** [comment]
You will also need to leave out the `bundle.yaml` from the templating step. The easiest way is to explicitly point ytt to your config or config directory. Here is an example:

```yaml
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: testtm
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  cluster: {}
  fetch:
  - imgpkgBundle:
      image: gcr.io/triggermesh/foo
  template:
  - ytt:
    paths:
    - <path-to-configmap-in-bundle>
  - kbld:
        paths:
        - "-"
        - .imgpkg/images.yml
  deploy:
  - kapp: {}
 ```

**Comment by sebgoa** [comment]
with a fixed indentation it worked

```
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: testtm
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - imgpkgBundle:
      image: gcr.io/triggermesh/foo
  template:
  - ytt:
      paths:
      - pod.yaml
  - kbld:
      paths:
      - "-"
      - .imgpkg/images.yml
  deploy:
  - kapp: {}
```

**Comment by ewrenn8** [comment]
Great, let us know if you've got any other questions!

@cppforlife @vibhas I wonder if it is worth adding some examples that build on the examples in the imgpkg docs to make this transition easier, especially as we start to reference imgpkg bundles more.

**Comment by sebgoa** [comment]
I finally managed to do what I wanted to test but this was not easy from the docs. Basically I wanted to package some plain old yaml which are not templatized and may not contain an image reference and then I wanted to deploy it with kapp controller.

turns out a simple:

```
imgpkg push -i gcr.io/triggermesh/barfoo -f pod.yaml 
```

don't use a bundle otherwise the error from `imgpkg` and the docs send you down the creation of a `.imgpkg` dir.

then create a `app.yaml` like so:

```
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: testtm
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - image:
      url: gcr.io/triggermesh/barfoo
  template:
  - ytt:  {}
  deploy:
  - kapp: {}
```

note the plain image reference and not the use of `imgpkgBundle` in the app spec.

I think this could be a bit more straightfoward from the docs.
