### ISSUE TITLE
deploying an App CR to a remote cluster using kapp-controller

### ISSUE THREAD

**Issue by zynpsnltrkk** [carvel-dev/kapp-controller#314]
I have 2 rke2 clusters. I want to deploy from the first cluster to the second cluster with a kapp controller.
here is my app cr
```
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: redis
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  cluster:
    namespace: default
    kubeconfigSecretRef:
      name: second-kubeconfig
  fetch:
  - helmChart:
      name: redis
      version: "12.10.1"
      repository:
        url: https://charts.bitnami.com/bitnami
  template:
  - helmTemplate:
      valuesFrom:
      - secretRef:
          name: redis-values
  deploy:
  - kapp:
      delete:
        # Force delete PVCs, since StatefulSet does not delete them
        rawOptions: ["--apply-ignored=true"]
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-values
  namespace: default
stringData:
  data.yml: |
    password: "1234567891234"
```
I created second-kubeconfig under the kubeconfigSecretRef with the following steps:

i got kubeconfig file from second cluster (second-cluster-kubeconfig.yaml)
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://10.0.0.x:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: ...
    client-key-data: ...
```
i encoded that file
```
cat second-cluster-kubeconfig.yaml | base64
```
i put that output into the secret and created the secret named second-kubeconfig in the first cluster.
```
apiVersion: v1
data:
  value: <..output...>
kind: Secret
metadata:
  name: second-kubeconfig
  namespace: default
type: Opaque
```
When I try to deploy app cr in my first cluster, target cluster still comes up as first cluster, not a second cluster. 
```
# kapp deploy -a redis -f redis-app.yaml
Target cluster 'https://127.0.0.1:6443' (nodes: ip-10-0-0-x, 2+)

Changes

Namespace  Name          Kind    Conds.  Age  Op      Op st.  Wait to    Rs  Ri
default    redis         App     -       -    create  -       reconcile  -   -
^          redis-values  Secret  -       -    create  -       reconcile  -   -

Op:      2 create, 0 delete, 0 update, 0 noop
Wait to: 2 reconcile, 0 delete, 0 noop

Continue? [yN]:
```
I couldn't find any examples of this and I'm not sure of my steps. can you help me about that?

**Comment by cppforlife** [comment]
looking over at your steps, they seem all right.

> When I try to deploy app cr in my first cluster, target cluster still comes up as first cluster, not a second cluster.

how are you determining that? can you run `kapp ls -A` on both clusters and share that output?

what version of kapp-controller are you using, btw?

**Comment by cppforlife** [comment]
ah noticed it. spec.serviceAccountName + spec.cluster is specified. when that happens serviceAccountName is preferred: https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/pkg/deploy/factory.go#L30-L41. just remove spec.serviceAccountName and it should work.

**Comment by zynpsnltrkk** [comment]
my first cluster:
```
Target cluster 'https://127.0.0.1:6443' (nodes: ip-10-0-0-x, 2+)

Apps in all namespaces

Namespace  Name        Namespaces                             Lcs   Lca
default    kc          (cluster),kapp-controller,kube-system  true  6h
^          redis-app   default                                -     26s
^          redis-ctrl  default                                -     14m

Lcs: Last Change Successful
Lca: Last Change Age

3 apps

Succeeded
```
my second cluster
```
Target cluster 'https://127.0.0.1:6443' (nodes: ip-10-0-0-y, 2+)

Apps in all namespaces

Namespace  Name  Namespaces                             Lcs   Lca
default    kc    (cluster),kapp-controller,kube-system  true  1h

Lcs: Last Change Successful
Lca: Last Change Age

1 apps

Succeeded
```
I am using the latest version (kapp deploy -a kc -f https://github.com/vmware-tanzu/carvel-kapp-controller/releases/latest/download/release.yml)
and cluster versions:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+rke2r1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-06-24T00:52:42Z", GoVersion:"go1.16.4b7", Compiler:"gc", Platform:"linux/amd64"}
```
I removed spec.serviceAccountName line but still the application deploys to the first cluster

**Comment by cppforlife** [comment]
> I removed spec.serviceAccountName line but still the application deploys to the first cluster

when you removed spec.serviceAccountName, it would not have deleted redis-ctrl from the 1st cluster, but i would expect it to deploy it to the second cluster.

**Comment by cppforlife** [comment]
(we dont currently support "smart" move from one cluster to another, where software would be deleted from one and reinstalled on another. first cluster would continue to carry deployed app. you can remove it via "kapp delete -a redis-ctrl -n ...")

**Comment by cppforlife** [comment]
@zynpsnltrkk so to circle back, was the app contents installed onto the second cluster (might have taken X amount of time e.g. 30s before next deploy happened)?

**Comment by zynpsnltrkk** [comment]
yes, it was deployed with the following app cr
```
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: redis
  namespace: default
spec:
        #  serviceAccountName: default-ns-sa
  cluster:
    namespace: default
    kubeconfigSecretRef:
      name: "second-kubeconfig"
      key: "value"
  fetch:
    - helmChart:
        name: redis
        version: "12.10.1"
        repository:
          url: https://charts.bitnami.com/bitnami
  template:
    - helmTemplate: 
        valuesFrom:
          - secretRef:
              name: redis-values
  deploy:
    - kapp:
        delete:
          # Force delete PVCs, since StatefulSet does not delete them
          rawOptions: ["--apply-ignored=true"]
```
in my first cluster
```
# kapp ls -A
Target cluster 'https://127.0.0.1:6443' (nodes: ip-10-0-0-x, 2+)

Apps in all namespaces

Namespace  Name    Namespaces                             Lcs   Lca
default   redis  default                               true  4h
default    kc      (cluster),kapp-controller,kube-system  true  5h

Lcs: Last Change Successful
Lca: Last Change Age

2 apps

Succeeded
```
kapp ls for second cluster
```
# kapp ls -A
Target cluster 'https://127.0.0.1:6443' (nodes: ip-10-0-0-y, 2+)

Apps in all namespaces

Namespace  Name         Namespaces                  Lcs   Lca
default    redis-ctrl  (cluster),default  true  4h

Lcs: Last Change Successful
Lca: Last Change Age

1 apps

Succeeded
```
thanks for your help
