### ISSUE TITLE
Documentation: Mention that imgpkg does not extract username/password out of auth key for private auth

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/kapp-controller#360]
For users of kapp-controller's [private auth feature](https://carvel.dev/kapp-controller/docs/latest/private-registry-auth/), we should call out that the Kubernetes Secret of type dockerconfigjson only supports username/password keys like below:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
            "auths": {
                    "<HOSTNAME:PORT>": {
                        "username": "testuser",
                        "password": "testpassword"
                    }
            }
    }
```

Some users may expect the following format to work in their Secrets:

```json
{
        "auths": {
                "<HOSTNAME:PORT>": {
                        "auth": "dGVzdHVzZXI6dGVzdHBhc3N3b3Jk"
                }
        }
}
```

imgpkg currently does not extract base64 encoded username/password under the auth key, so we should try to call out in kapp-controller's private auth docs that this format will not work.

A possible place to add this information would be in the [bringing it all together section of the docs](https://carvel.dev/kapp-controller/docs/latest/private-registry-auth/#bringing-it-all-together).
