### ISSUE TITLE
[fetch] support custom ca cert for image pulling

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#39]

**Comment by cppforlife** [comment]
from @jessehu :

1. When executing 'imgpkg' on a local machine, we can add the self-signed CA certificate on the local machine to fix it.
2. When executing 'imgpkg' in a container (e.g. kapp-controller), does it work? If not, we might need to add an option in App CR (around fetch.image.url) for specifying CA cert.

This is simliar to https://github.com/vmware-tanzu/carvel-kapp-controller/issues/42

**Comment by arfiqbal** [comment]
Even i am facing this issue from private registry
  Fetching registry image: Imgpkg: exit status 1 (stderr: Error: Collecting images: Working with registry.XXXXX.com/library/tkg-extensions-templates:v1.2.0_vmware.1: Get https://registry.XXXXX.com/v2/: x509: certificate signed by unknown authority

```spec:
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
  fetch:
  - image:
      url: registry.XXXXX.com/library/tkg-extensions-templates:v1.2.0_vmware.1
  serviceAccountName: prometheus-extension-sa
  syncPeriod: 5m
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        pathsFrom:
        - secretRef:
            name: prometheus-data-values
      paths:
      - tkg-extensions/common
      - tkg-extensions/monitoring/prometheus
```
How do i add certificate or way to skip it

**Comment by danielhelfand** [comment]
@arfiqbal Thanks for pointing out this issue. As [documented above](https://github.com/vmware-tanzu/carvel-kapp-controller/issues/39#issuecomment-728962181), `kapp-controller` does not support custom ca certs, but the underlying tool (`imgpkg`) does support a `--registry-ca-cert-path`. 

Unfortunately, we need a way to specify options for `imgpkg pull` to avoid scenarios like this. So I am not sure if there is a workaround with `kapp-controller` at this moment.

**Comment by cppforlife** [comment]
@arfiqbal 

> How do i add certificate or way to skip it

you can do that today by either builder a new image that inherits from kapp-controller and adding your own CA bundle or figuring out a way to inject CA bundle at runtime before through init container.

this issue will track work for making this feature a first class feature and will be available in one of the future releases.

**Comment by arfiqbal** [comment]
@cppforlife @danielhelfand 
Let me know the path where we can add the custom CA ? so that i'll try to mount the ca cert using configmap

**Comment by jessehu** [comment]
@arfiqbal assuming you have put the CA cert file of the private registry under /etc/ssl/certs/harbor-ca.crt (file mode 644) on your k8s worker nodes, you can make the following change to the kapp-controller deployment, then imgpkg inside the kapp-controller will be able to pull images from registry.XXXXX.com.

```
      containers:
      - command:
        - /kapp-controller
        env:
        - name: KAPPCTRL_MEM_TMP_DIR
          value: /etc/kappctrl-mem-tmp
        image: registry.yourdomain.com/kapp-controller:v0.9.0
        imagePullPolicy: IfNotPresent
        name: kapp-controller

        volumeMounts:
        - mountPath: /etc/kappctrl-mem-tmp
          name: template-fs
        - mountPath: /etc/ssl/certs/harbor-ca.crt
          name: certs
          subPath: harbor-ca.crt

      volumes:
      - emptyDir:
          medium: Memory
        name: template-fs
      - hostPath:
          path: /etc/ssl/certs
          type: ""
        name: certs
```

**Comment by arfiqbal** [comment]
@jessehu  we tried the exactly the same thing but still no luck
```
    spec:
      containers:
      - command:
        - /kapp-controller
        env:
        - name: KAPPCTRL_MEM_TMP_DIR
          value: /etc/kappctrl-mem-tmp
        image: registry.xxxxx.com/kapp-controller:v0.9.0_vmware.1
        imagePullPolicy: IfNotPresent
        name: kapp-controller
        resources:
          requests:
            cpu: 120m
            memory: 100Mi
        securityContext:
          runAsGroup: 2000
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kappctrl-mem-tmp
          name: template-fs
        - mountPath: /etc/ssl/certs/harbor-ca.crt
          name: cert
          subPath: harbor-ca.crt
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 3000
      serviceAccount: kapp-controller-sa
      serviceAccountName: kapp-controller-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: template-fs
      - hostPath:
          path: /etc/ssl/certs
          type: ""
        name: cert
```
```
arif@de1gks1tkg:~$ oc get apps.kappctrl.k14s.io
NAME         DESCRIPTION   SINCE-DEPLOY   AGE
prometheus   Reconcile failed: Fetching (0): Fetching registry image: Imgpkg: exit status 1 (stderr: Error: Collecting images: Working with registry.xxxxx.com/library/tkg-extensions-templates:v1.2.0_vmware.1: Get https://registry.xxxxx.com/v2/: x509: certificate signed by unknown authority
)                          85s
```

**Comment by jessehu** [comment]
@arfiqbal /etc/ssl/certs/harbor-ca.crt must exists on every worker nodes, and the file mode must be worldwide readable.  BTW I will try the Secret/ConfigMap approach later.

**Comment by arfiqbal** [comment]
@jessehu yup, I have copied the harbor-ca.crt in all the worker node and i also tried with configmap but its still not working

Thanks for your quick response :)

**Comment by jessehu** [comment]
Also make sure your harbor-ca.crt is correct. Running the following command on worker nodes should succeed if /etc/ssl/certs/harbor-ca.crt contains the correct CA of your Harbor Registry.

`imgpkg pull --image registry.xxxxx.com/library/tkg-extensions-templates:v1.2.0_vmware.1 --output /tmp/1`

**Comment by arfiqbal** [comment]
@jessehu 
i tried from one of my worker node and its working perfectly

```
root@gks-rat-stg-5-md-0-6f77987df7-zvhd6 [ ~ ]# imgpkg pull --image registry.xxxxx.com/library/tkg-extensions-templates:v1.2.0_vmware.1 --output /tmp/1
Pulling image 'registry.xxxxx.com/library/tkg-extensions-templates@sha256:b9825280fd44c012b97b92ebf24b3b7fd2af4bbbe11c3901d350432ae828451e'
Extracting layer 'sha256:46c40ce88d5394ceb4350e8c2a3b8f9f160cd9b3bdea5d6317f2a14c244ed1e6' (1/1)

Succeeded

```

**Comment by jessehu** [comment]
How about the file mode 'ls -l /etc/ssl/certs/harbor-ca.crt' ? If it's worldwide readable, then I have no other idea.

**Comment by arfiqbal** [comment]
Here it is
```
root@gks-rat-stg-5-md-0-6f77987df7-zvhd6 [ ~ ]# ls -l /etc/ssl/certs/harbor-ca.crt
-rw-r--r-- 1 root root 2508 Dec  3 08:35 /etc/ssl/certs/harbor-ca.crt

```

**Comment by arfiqbal** [comment]
@jessehu 
Now i am getting different issue
```
arif@de1gks1tkg$ oc get apps.kappctrl.k14s.io
NAME         DESCRIPTION                                       SINCE-DEPLOY   AGE
prometheus   Reconcile failed: Templating dir: exit status 1                  4m16s

```

**Comment by jessehu** [comment]
The certificate issue in kapp-controller is resolved. You can email me at huh@vmware.com to debug this new issue.

**Comment by arfiqbal** [comment]
@jessehu  sure mate :)

Can you let me know what are the information your are looking for ?

**Comment by sharmavijay86** [comment]
HI @jessehu   The error in detail is bellow . Some templating which is not able to predict the platform infra . btw we are using tkg on vpshere.

```
  inspect:
    error: 'Inspecting: exit status 1'
    exitCode: 1
    stderr: 'kapp: Error: App ''prometheus-ctrl'' (namespace: tanzu-system-monitoring)
      does not exist: configmaps "prometheus-ctrl" not found'
    stdout: Target cluster 'https://100.64.0.1:443'
    updatedAt: "2020-12-03T10:06:14Z"
  observedGeneration: 1
  template:
    error: 'Templating dir: exit status 1'
    exitCode: 1
    stderr: "ytt: Error: \n- cannot load values.star: Evaluating starlark template:
      \n    in <toplevel>\n      00-server-namespace.yaml:1 | #@ load(\"values.star\",
      \"values\")\n\n    reason:\n     - assert.fail: fail: infrastructure provider
      should be either aws or vsphere or azure\n         in validate_infrastructure_provider\n
      \          9 |   data.values.infrastructure_provider in (\"aws\", \"vsphere\",
      \"azure\") or assert.fail(\"infrastructure provider should be either aws or
      vsphere or azure\")\n         in validate_pushgateway\n           195 |     validate_func()\n
      \        in <toplevel>\n           255 | validate_pushgateway()\n"
    updatedAt: "2020-12-03T10:06:14Z"
```

**Comment by jessehu** [comment]
Thanks @sharmavijay86. You didn't set `infrastructure_provider: vsphere` in the values.yaml. Please email me for further questions or find another place like Slack to discuss it, as this issue not related to kapp-controller.

**Comment by arfiqbal** [comment]
@jessehu Just mailed you with all the information... Please check

**Comment by jessehu** [comment]
Here is the ConfigMap solution for supporting custom ca cert for image pulling:

1. Add the CA cert of your registry server into a file custom-ca-certs.crt

2. Create a ConfigMap with this file:
kubectl create configmap custom-ca-certs --from-file=custom-ca-certs.crt -n kapp-controller

3. Modify the kapp-controller.yaml as below to mount the cert file from the ConfigMap, then kubectl apply it.

```
containers:
- command:
  - /kapp-controller
  ... ...
  volumeMounts:
  - mountPath: /etc/kappctrl-mem-tmp
    name: template-fs
  - mountPath: /etc/ssl/certs/custom-ca-certs.crt
    name: custom-ca-certs
    readOnly: true
    subPath: custom-ca-certs.crt
... ...
volumes:
- emptyDir:
    medium: Memory
  name: template-fs
- configMap:
    name: custom-ca-certs
  name: custom-ca-certs
```
