### ISSUE TITLE
Run Package Repository through a ytt processor when getting the resulting Packages

### ISSUE THREAD

**Issue by voor** [carvel-dev/kapp-controller#397]
**Describe the problem/challenge you have**
I am taking a Package Repository from somewhere upstream, and I would like to add additional overlays into this bundle.  I want to preserve the original files without modification, so ytt is the most logical choice to use for applying overlays.

**Describe the solution you'd like**
Given a folder that looks like this:
```
.
├── config
│   └── overlay.yaml
├── .imgpkg
│   └── images.yml
└── packages
    └── packages.yaml
```

I would like this to be processed through ytt:
```
ytt -f .
```
prior to being processed by whatever it's running through.

**Anything else you would like to add:**
The imgpkg bundle is being relocated from one location to another, after push a copy is conducted.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
hmm, im not sure how i feel about storing overlays in a package repository bundle vs elsewhere. pkg repository has a particular fs format (e.g. packages/ dir) and possible will evolve over time.

**Comment by aaronshurley** [comment]
After some discussion between @cppforlife and @voor, this feature may not be as helpful as initially expected. Closing this out for now but we can reopen if needed.

**Comment by voor** [comment]
For historical purposes.  Initially this was because we were applying overlays to several packages (insert `ytt` to places that didn't have it, or `kbld`, etc.) later on we started doing overlays to everything:

```
#@ def package_overlay():
kind: Package
#@ end

#@overlay/match by=overlay.subset(package_overlay()),expects="11+"
---
spec:
  template:
    spec:
      deploy:
      #@overlay/match by=lambda _,l,r: "kapp" in l
      - kapp:
          #@overlay/match missing_ok=True
          rawOptions:
          - --wait-timeout=5m
          - --diff-changes=true
```

Over time we found we needed to do other stuff, `vendir` related and `imgpkg copy` and things that basically required an intermediary step of bash-like opportunity to easily pipe `ytt` in there.  Since adding overlay capability to a PackageRepository would not address the need for the other steps we would very likely keep the pipe to `ytt` in the bash-like phases anyway, so this feature would not be adopted even if it was added.
