### ISSUE TITLE
[fetch] support http proxy configuration

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#41]
seems like this should be per controller configuration? at the least, document how to configure env vars.

example env vars:

```yaml
- name: http_proxy 
  value: http://proxy.corp.com:8888
- name: HTTP_PROXY
  value: http://proxy.corp.com:8888
- name: https_proxy 
  value: http://proxy.corp.com:8888
- name: HTTPS_PROXY
  value: http://proxy.corp.com:8888
- name: no_proxy
  value: 127.0.0.1,localhost,kubernetes.default.svc,.svc,.corp.com
- name: NO_PROXY
  value: 127.0.0.1,localhost,kubernetes.default.svc,.svc,.corp.com
- name: PROXY_ENABLED
  value: "yes"
```
