### ISSUE TITLE
kapp-controller forces to create a namespace that then gets ignored when doing a remote deployment

### ISSUE THREAD

**Issue by mpermar** [carvel-dev/kapp-controller#415]
**What steps did you take:**

Have an application that sets a target namespace on a cluster but also on the metadata level. Like this one here:

```yaml
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-app
  namespace: default
spec:
  cluster:
    namespace: carvel-apps
    kubeconfigSecretRef:
      name: kubeconfigsecret
      key: value
```

**What happened:**

When you try to deploy an application like that one, kapp-controller will fail the deployment and force you to create the _carvel-apps_ namespace in the target cluster. Then deployment succeeds, but if you check the carvel-apps namespace there will be nothing there. The app gets deployed in the _default_ namespace.

**What did you expect:**

I would expect from kapps-controller to deploy the application in the target namespace that has forced me to create. However, if kapps-controller detected this and didn't ask me to create the namespace, that would be equally fine. 

**Anything else you would like to add:**

What I did understood from the docs was that the namespace at the top level was going to be the default but that would be overwritten by the cluster level namespace. Perhaps this misunderstanding is just a documentation issue, I don't know.

```yaml
  # specifies that app should be deployed to destination cluster;
  # by default, cluster is same as where this resource resides (optional; v0.5.0+)
  cluster:
    # specifies namespace in destination cluster (optional)
    namespace: ns2
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joe-kimmel-vmw** [comment]
@mpermar Thanks for reporting this!

Can you describe in a little more detail the steps necessary to reproduce this bug?  Did you have a multi-cluster environment? did you use `kapp deploy ...` on something similar to the spec above?   Do you think the `kubeconfigSecretRef` block is necessary to reproduce, or would you expect it to happen even with just a cluster/namespace specified?

**Comment by mpermar** [comment]
@joe-kimmel-vmw this can be reproduced with this simple application:

```yaml
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-app-2
  namespace: default
spec:
  cluster:
    namespace: carvel-apps
    kubeconfigSecretRef:
      name: kubeconfigsecret
      key: value
  fetch:
  - git:
      url: https://github.com/vmware-tanzu/carvel-simple-app-on-kubernetes
      ref: origin/develop
      subPath: config-step-2-template
  template:
  - ytt: {}
  deploy:
  - kapp: {}
```

Then with two clusters. One runs kapp-controller, the other is the target cluster that kubeconfigsecret points to. If you try to deploy this application with "_kubectl -f apply_" and not doing any other steps, what will happen is that you will get an error complaining about the target namespace not being found.

```
  friendlyDescription: Reconciling
  inspect:
    error: 'Inspecting: Error (see .status.usefulErrorMessage for details)'
    exitCode: 1
    stderr: 'kapp: Error: App ''simple-app-2-ctrl'' (namespace: carvel-apps) does
      not exist: configmaps "simple-app-2-ctrl" not found'
    stdout: Target cluster 'https://0BC7951A26AA51343F814E02409425F8.gr7.us-west-2.eks.amazonaws.com'
    updatedAt: "2021-12-09T15:16:39Z"
  observedGeneration: 1
  template:
    exitCode: 0
    updatedAt: "2021-12-09T15:17:10Z"
  usefulErrorMessage: 'kapp: Error: Creating app: namespaces "carvel-apps" not found'
```

If, subsequently you create the _carvel-apps_ namespace in the target cluster, then reconciliation will succeed but the app gets deployed at the default namespace. I presume, without having looked at the code or knowing how the internals work, that kapp-controller tries to put some metadata in configmaps at the target namespace, but then ends up installing the application in a different namespace. 

To me the above is quite misleading. If not, then the documentation might need to be modified accordingly.
