### ISSUE TITLE
implement spec.template[].ytt.inline.pathsFrom[].secretRef.directoryPath

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#421]
**Describe the problem/challenge you have**
currently it seems that even though api has directoryPath, that functionality is not implemented (directory would need to be explicitly created).

repro:

```yaml
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-app
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - inline:
      paths:
        file-from-fetch-paths: ""
        # something/blah.txt: ""
      pathsFrom:
        - secretRef:
            name: from-secret
            directoryPath: dir
  template:
  - ytt:
      inline:
        # pathsFrom:
        # - secretRef:
        #     name: foo
        #     # NOT IMPLEMENTED -- results in an error
        #     directoryPath: something
        paths:
          config.yml: |
            #@ load("@ytt:data", "data")
            #@ load("@ytt:yaml", "yaml")
            
            #@ print(data.list())

            kind: ConfigMap
            apiVersion: v1
            metadata:
              name: foo
            data:
              data: #@ yaml.encode(data.list())
  deploy:
  - kapp: {}
---
kind: Secret
apiVersion: v1
metadata:
  name: from-secret
stringData:
  file-from-secret: ""
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
```yaml
# specified content via secrets and config maps;
# data values are recommended to be placed in secrets (optional)
pathsFrom:
  - secretRef:
      name: secret-name
      # specifies where to place files found in secret (optional)
      directoryPath: dir
  - configMapRef:
      name: cfgmap-name
      # specifies where to place files found in config map (optional)
      directoryPath: dir
```

The above documentation provides more details on how this is supposed to work. One thing that was a little confusing to me is why this feature is offered for templating inline versus user being required to fetch the secret. Why should we not just remove this property all together?
