### ISSUE TITLE
support path for helm template templater

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#44]
proposed changes
- add path to indicate where chart is
- add ability to load values from a file path
- raw options?

```
  - helmTemplate:
      name: external-dns
      path: helm/chart #! Tell helm template where to find the chart location
      valuesFrom:
      - fileRef: helm/external-dns-values.yaml #! Tell helm an additional file to pass as a -f option
      - fileRef: helm/secret-external-dns-values.yaml #! Tell helm an additional file to pass as a -f option
      - secretRef:
          name: secrets-that-were-setup-ahead-of-time-for-helm
      rawOptions:
      - "--namespace external-dns"
      - "--include-crds"
```

(https://raw.githubusercontent.com/voor/kapp-controller-helm-pipeline/main/external-dns/app/external-dns.yaml)
