### ISSUE TITLE
Support for insecure registries

### ISSUE THREAD

**Issue by benmoss** [carvel-dev/kapp-controller#502]
**Describe the problem/challenge you have**
I'm trying to use a [docker-based local registry](https://kind.sigs.k8s.io/docs/user/local-registry/) to store my bundles. The registry is reachable from the kapp-controller pod via a containerd mirror, but kapp-controller assumes the registry will speak https and fails.

```
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: test
spec:
  fetch:
    imgpkgBundle:
      image: kind-registry:5000/repo:v1
```

The PackageRepository fails to reconcile and gives me this error:
```
Useful Error Message:  vendir: Error: Syncing directory '0':
  Syncing directory '.' with imgpkgBundle contents:
    Imgpkg: exit status 1 (stderr: imgpkg: Error: Checking if image is bundle:
  Fetching image:
    Get "https://kind-registry:5000/v2/": http: server gave HTTP response to HTTPS client
)
```

**Describe the solution you'd like**
Maybe we can add an `insecure` field to `imgpkgBundle` to tell it to not force HTTPS.

**Anything else you would like to add:**
Not sure where the HTTPS enforcement is happening. `imgpkg pull` and `push` work, `vendir sync` works without `dangerouSkipTLSVerify: true`

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
