### ISSUE TITLE
surface in App CR status set of namespaces used for the deployment

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#535]
**Describe the problem/challenge you have**
[A description of the current challenge that you are experiencing.]

it's useful for users of App CR and PackageInstall CR to know which namespaces hold deployed resources. internally `kapp ls` presents a list of used namespaces, however such information would only be accessible to direct kapp CLI users. it would be nice to somehow surface this info in App CR status, e.g.

```yaml
status:
  deploy:
     usedNamespaces:
     - "" # empty to represent cluster-scope
     - knative-serving
     - knative-eventing
```

**Describe the solution you'd like**
[A clear and concise description of what you want to happen. If applicable a visual representation of the UX.]

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

this problem might be also generally related to letting users identify what are resources that are part of this app/packageinstall.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joe-kimmel-vmw** [comment]
@cppforlife in discussion with @benmoss @neil-hickey we're wondering if it's worth a discussion re. solving the full case of "letting users identify what resources are part of this app/pkgi" vs the special case of just namespaces?

**Comment by cppforlife** [comment]
possibly. though, i could see how identifying all resources might be an expensive operation vs identifying namespaces at the time of the deploy might be cheap. would love to hear ideas on more generic api though.

**Comment by benmoss** [comment]
We have the resources at deploy time, right? I think this is a good example of a case where if we were using a kapp SDK this would be easy, but instead all that data is lost inside the CLI. 

```yaml
status:
  deploy:
     resources:
     - {apiVersion: "v1", kind: "Namespace", name: "knative-serving"}
     - {apiVersion: "v1", kind: "ServiceAccount", name: "knative-serving", namespace: "knative-serving"}
 ```
