### ISSUE TITLE
[fetch] Add config for fetching imgpkg bundles

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#57]
**Describe the problem/challenge you have**
There is currently no way to fetch assets stored in an imgpkg bundle.

**Describe the solution you'd like**
A section of the AppCRD that contains info for fetching an imgpkg bundle.

```yaml
spec:
  fetch:
    imgpkgBundle:
        # Image url; unqualified, tagged, or
        # digest references supported (required)
        url: host.com/username/image:v0.1.0
        # secret with auth details (optional)
        secretRef:
          name: secret-name
        # grab only portion of image (optional)
        subPath: inside-dir/dir2
```

This would allow users to leverage the benefits of imgpkg bundles over images, for example, using the ImagesLock file during the template stage for relocated assets .
