### ISSUE TITLE
helmChart fetch broken for OCI source repositories

### ISSUE THREAD

**Issue by st3v** [carvel-dev/kapp-controller#588]
In version 3.7.0 of Helm the `helm chart pull` command was replaced with `helm pull` (see [release notes](https://github.com/helm/helm/releases/tag/v3.7.0)). That change does not seem to be reflected in `vendir`'s OCI source yet (see [here](https://github.com/vmware-tanzu/carvel-vendir/blob/1655a8e5ca8dcc3e9535aedd3617b7a3bb7dca15/pkg/vendir/fetch/helmchart/oci_source.go#L134)), which would be okay if  kapp-controller wouldn't be pulling in Helm v3.8.0 (see [here](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/e6f78c7ab1f2a0e8e6a958375ef0c517fc198dbd/Dockerfile#L35)).

**What steps did you take:**
Create `App`...

```
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tanzu-postgresql-operator
spec:
  fetch:
    - helmChart:
        name: tanzu-sql-postgres/postgres-operator-chart
        version: "v1.6.1"
        repository:
          url: oci://registry.tanzu.vmware.com
          secretRef:
            name: repo-creds
...
```

**What happened:**
`App` status shows the following error...

```
usefulErrorMessage: |
      vendir: Error: Syncing directory '0':
        Syncing directory '.' with helm chart contents:
          Helm chart pull: exit status 1 (stderr: Error: unknown command "chart" for "helm"
      Run 'helm --help' for usage.
      )
```

**What did you expect:**
It pulls the chart as expected.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- kapp Controller version: v0.34.0
- Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
