### ISSUE TITLE
Kapp controller's `spec.fetch.imgpkgBundle.secretRef` doesn't support `dockerconfigjson` type  secrets

### ISSUE THREAD

**Issue by mohansitaram** [carvel-dev/kapp-controller#592]
**What steps did you take:**

1. Logged into my registry by doing "docker login". This updates my "~/.docker/config.json" with the registry authentication credentials. 
2. Created a secret of type "docker-registry " using the following command `kubectl create secret docker-registry my-secret --from-file=.dockerconfigjson="/root/.docker/config.json"`
4. I referenced this secret in my App CR:
 ```

kubectl describe app my-app | grep -B 3 -A 3 "Secret Ref"
  Fetch:
    Imgpkg Bundle:
      Image:  10.180.13.169:30001/tcx/my-app:latest
      Secret Ref:
        Name:           my-secret   
  Service Account Name:  cluster-admin-sa
```

**What happened:**
Kapp controller fails to pull the imgpkg bundle from the registry with the provided credentials in the secret. Output of `kubectl describe app`
```
Status:
  Conditions:
    Message:                       Fetching resources: Error (see .status.usefulErrorMessage for details)
    Status:                        True
    Type:                          ReconcileFailed
  Consecutive Reconcile Failures:  15
  Fetch:
    Error:       Fetching resources: Error (see .status.usefulErrorMessage for details)
    Exit Code:   1
    Started At:  2022-03-29T10:11:59Z
    Stderr:      vendir: Error: Syncing directory '0':
  Syncing directory '.' with imgpkgBundle contents:
    Imgpkg: exit status 1 (stderr: imgpkg: Error: Checking if image is bundle:
  Fetching image:
    GET http://10.180.13.169:30001/v2/tcx/my-app/manifests/latest:
      UNAUTHORIZED: unauthorized to access repository: tcx/my-app, action: pull: unauthorized to access repository: tcx/my-app, action: pull
)

    Updated At:          2022-03-29T10:12:06Z
  Friendly Description:  Reconcile failed: Fetching resources: Error (see .status.usefulErrorMessage for details)
  Observed Generation:   1
  Useful Error Message:  vendir: Error: Syncing directory '0':
  Syncing directory '.' with imgpkgBundle contents:
    Imgpkg: exit status 1 (stderr: imgpkg: Error: Checking if image is bundle:
  Fetching image:
    GET http://10.180.13.169:30001/v2/tcx/my-app/manifests/latest:
      UNAUTHORIZED: unauthorized to access repository: tcx/my-app, action: pull: unauthorized to access repository: tcx/my-app, action: pull
```

**What did you expect:**
Kapp controller to use the credentials provided in the secret to fetch the bundle from the registry.

**Anything else you would like to add:**
The contents of my "/root/.docker/config.json" are correct. I am able to push/pull images directly to the registry from where I ran `docker login`. 
This functionality is critical for security reasons. A user should not have to provide their registry's authentication credentials in plain text to create a secret. They should be able to create a secret that inherits the credentials from `~/.docker/config.json` and `kapp-controller` should be able to use this secret to pull artifacts from the registry.

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
```
    kapp-controller.carvel.dev/version: v0.33.1
    kapp.k14s.io/identity: v1;default/apps/Deployment/kapp-controller;apps/v1
    kapp.k14s.io/original: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kapp-controller.carvel.dev/version":"v0.33.1","kbld.k14s.io/images":"-
      Metas:\n  - Type: preresolved\n    URL: 10.180.13.169:30001/tcx/kapp-controller@sha256:a97d9d43b8b5d996f6510ae88ee761ac0f1d883d04fa7402b32f8ce6f9f875bd\n  URL:
      10.180.13.169:30001/tcx/kapp-controller@sha256:a97d9d43b8b5d996f6510ae88ee761ac0f1d883d04fa7402b32f8ce6f9f875bd\n"},"labels":{"kapp.k14s.io/app":"1648513119142012265","kapp.k14s'
    kapp.k14s.io/original-diff-md5: 870739d9e2d7ec723b283caa912e35a4
    kbld.k14s.io/images: |
      - Metas:
        - Type: preresolved
          URL: 10.180.13.169:30001/tcx/kapp-controller@sha256:a97d9d43b8b5d996f6510ae88ee761ac0f1d883d04fa7402b32f8ce6f9f875bd
        URL: 10.180.13.169:30001/tcx/kapp-controller@sha256:a97d9d43b8b5d996f6510ae88ee761ac0f1d883d04fa7402b32f8ce6f9f875bd
```
- Kubernetes version (use `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z",}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z",}
```
---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
