### ISSUE TITLE
app cr downward api to pass info as values into templating

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#659]
**Describe the problem/challenge you have**

there have been a few cases where we want to pass info about App CR as values into templates:
- App CR name and namespace so that resources can be customized
  - if i am creating multiple App CRs in the same namespace, i would like to avoid users having to manually specify unique name (App CR name would be unique within a namespace, or in cluster if it's namespace+name)
- App CR annotations/labels
  - may want to propagate certain annotations to created resources
- App CR uid
- App CR fetch information (vendir.lock.yml)
  - may want to include git info about where content came from as an annotation on a resource

**Describe the solution you'd like**

something along these lines... (existing valuesFrom expanded)
```yaml
valuesFrom:
- secretRef:
    name: secret-name
- configMapRef:
    name: cfgmap-name
- path: values/shared.yml
# new type downwardAPI
- downwardAPI:
    items:
    - name: namespace
      fieldPath: metadata.namespace
    - name: name
      fieldPath: metadata.name
    - name: somewhere.source
      vendirLock: {} # since it's not a field on App CR
```

**Anything else you would like to add:**

prior art for downward API in Pods -- https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
