### ISSUE TITLE
Cryptic errors when using an invalid PackageRepository

### ISSUE THREAD

**Issue by benmoss** [carvel-dev/kapp-controller#760]
**What steps did you take:**
Tried to create a PackageRepository that was actually not a PackageRepository bundle. Got this error:

```
NAME:          tbs-repository
VERSION:       2275761
REPOSITORY:    index.docker.io/ajitone/build-service
TAG:           1.5.2
STATUS:        Reconcile failed: Templating dir: Error (see .status.usefulErrorMessage for details)
REASON:        ytt: Error: Checking file '/etc/kappctrl-mem-tmp/kapp-controller-fetch-template-deploy759612810/0/packages': lstat /etc/kappctrl-mem-tmp/kapp-controller-fetch-template-deploy759612810/0/packages: no such file or directory
```

**What happened:**
I will fill in more details / better repro, just jotting this down now.

**Comment by joe-kimmel-vmw** [comment]
Thanks for filing this issue @benmoss!  Please do tell us more about your use-case and how to reproduce this bug.

**Comment by benmoss** [comment]
This came out of a support request, a user had copied an imgpkg repository bundle to their Docker Hub account and then mistakenly used the wrong image as the repository image.

This repo is a decent repro of the core problem, which is just better error handling when a repo doesn't match the repo file structure

```yaml
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: some-repo
spec:
  fetch:
    inline:
      paths:
        derp: hi
```
