### ISSUE TITLE
Don't run kapp inspect if we haven't successfully deployed

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kapp-controller#77]
**What steps did you take:**
1. Deploy an app that has a failing fetch stage:
```yaml
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-app
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - http:
      url: i-dont-exist
  template:
  - ytt: {}
  deploy:
  - kapp: {}
```
2. `kubectl get apps -n <namespace you deployed to> -oyaml`
3. see that status has an inspect stage showing an error

**What happened:**
Seeing the inspect error, which isnt the actual error causing reconciliation to fail, is misleading
```yaml
    fetch:
      error: 'Fetching resources: exit status 1'
      exitCode: 1
      startedAt: "2021-01-27T19:33:30Z"
      stderr: |
        Error: Syncing directory '0': Syncing directory '.' with HTTP contents: Downloading URL: Initiating URL download: Get i-dont-exist: unsupported protocol scheme ""
      updatedAt: "2021-01-27T19:33:30Z"
    friendlyDescription: 'Reconcile failed: Fetching resources: exit status 1'
    inspect:
      error: 'Inspecting: exit status 1'
      exitCode: 1
      stderr: 'kapp: Error: App ''simple-app-ctrl'' (namespace: default) does not
        exist: configmaps "simple-app-ctrl" not found'
      stdout: Target cluster 'https://10.96.0.1:443'
      updatedAt: "2021-01-27T19:33:30Z"
```

**What did you expect:**
To just see the error that relates to why the app is failing (in this case the fetch)

We should not run inspect if the app has never been deployed.
