### ISSUE TITLE
Is there a way to configure the merge strategy for the kapp-controller when reconciling the service resources? 

### ISSUE THREAD

**Issue by YuxinZhou** [carvel-dev/kapp-controller#825]
Hi carvel team, 

We hit a problem when installing the Harbor package (https://github.com/vmware-tanzu/community-edition/tree/main/addons/packages/harbor) on our cluster. Would appreciate it if you could give some suggestions on this. 

The problem is that the Harbor service will create some PVCs. On our cluster, the PVCs are also reconciled by another controller called CSI. The CSI controller will patch an annotation  `volumehealth.storage.kubernetes.io/health` to the PVC resource and it prevents all other controllers/users from updating that annotation, via a webhook. However the kapp-controller would try to update the PVCs and remove the annotation periodically, thus we got the error: 

```
kapp: Error: Applying update persistentvolumeclaim/harbor-jobservice (v1) namespace: svc-harbor-domain-c9:
  Updating resource persistentvolumeclaim/harbor-jobservice (v1) namespace: svc-harbor-domain-c9:
    API server says: admission webhook "validation.csi.vsphere.vmware.com" denied the request:
      PVC Annotation volumehealth.storage.kubernetes.io/health is not mutable by user system:serviceaccount:vmware-system-supervisor-services:default-carvel-install-sa (reason: PVC Annotation volumehealth.storage.kubernetes.io/health is not mutable by user system:serviceaccount:vmware-system-supervisor-services:default-carvel-install-sa)
```

My questions are: 
1. Is this expected that the kapp-controller is removing the annotation added by other controllers? 
2. Is there a way to configure this? Maybe allow the admin to configure the merge strategy for kapp-controller when reconciling the service resources? 

Thank you in advance.

**Comment by praveenrewar** [comment]
Hi @YuxinZhou !

> Is this expected that the kapp-controller is removing the annotation added by other controllers?

Yeah, this is an expected behaviour.

> Is there a way to configure this? Maybe allow the admin to configure the merge strategy for kapp-controller when reconciling the service resources?

You can use an [overlay](https://carvel.dev/kapp-controller/docs/v0.38.0/package-install-extensions/) to add this annotation or  [kapp rebase rules](https://carvel.dev/kapp/docs/v0.51.0/config/#rebaserules) to copy fields (in this case the volume heath annotation) from the resource present in cluster so that kapp doesn't try to remove it in further reconciliations.
(kapp rebase rules explicitly define how to merge resources during update)

Update: Here's a [thread](https://kubernetes.slack.com/archives/C02GY94A8KT/p1652192286282799?thread_ts=1652192286.282799&cid=C02GY94A8KT) I found on TCE slack channel about something similar.

**Comment by YuxinZhou** [comment]
Hi @praveenrewar, Thank you a lot for your quick response! 

Regarding the overlay solution,  I forgot to mention that the annotation `volumehealth.storage.kubernetes.io/health` has a value (`accessible`, `inaccessible`, etc ) that the CSI  controller reconciles. So we don't want to patch a hard-coded annotation.  Could the overlay solutions be applied for such a use case? 

The rebase rules look like what we want, and there is a similar scenario for [PVC](https://carvel.dev/kapp/docs/v0.51.0/rebase-pvc/) mentioned in the documentation. But that is for kapp CLI. Is there a way to apply the same configuration to the kapp-controller? 

Many thanks,
Yuxin

**Comment by praveenrewar** [comment]
Hi @YuxinZhou 

The annotation `ext.packaging.carvel.dev/ytt-paths-from-secret-name` can be used to add overlays to PackageInstalls (in this case it would add additional kapp config), it might look something like this:
 
```yaml
 ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: harbor-secret-overlay
  stringData:
    harbor-secret-overlay.yaml: |
      ---
      apiVersion: kapp.k14s.io/v1alpha1
      kind: Config
  
      rebaseRules:
      - path: [metadata, annotation, volumehealth.storage.kubernetes.io/health]
        type: copy
        sources: [existing]
        resourceMatchers:
        - apiVersionKindMatcher: {apiVersion: v1, kind: PersistentVolumeClaim}
```
